name: 'Hello World '
description: 'A composite action that prints Hello World'
runs:
  using: 'composite'
  steps:
    - name: Print Hello World
      run: echo "Hello file yml"
      shell: bash  # Add this line
