name: Example Reusable Workflow

on:
  workflow_call:


jobs:
  echo_job:
    runs-on: ubuntu-latest
    outputs:
      echo_output: ${{ steps.echo_step.outputs.result }}
    steps:
      - name: Echo Message
        id: echo_step
        run: echo "Hello world"
