name: Example Reusable Workflow

on:
  workflow_call:

jobs:
  echo_job:
    runs-on: ubuntu-latest
    outputs:
       build_status: ${{ job.status }}
    steps:
      - name: Echo Reusable Message
        id: echo_step
        run: echo "Hello world"
