name: Example Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        type: string
        required: true
    outputs:
      result:
        description: "Result of the workflow"
        value: ${{ steps.echo_step.outputs.result }}

jobs:
  echo_job:
    runs-on: ubuntu-latest
    outputs:
      echo_output: ${{ steps.echo_step.outputs.result }}
    steps:
      - name: Echo Message
        id: echo_step
        run: echo "::set-output name=result::$message"
