on:
  workflow_call:

jobs:
  Smoke-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List
        run: |
          ls -la >> $GITHUB_STEP_SUMMARY
